---
- name: Fetch PhpMetrics latest release version.
  uri:
    url: https://api.github.com/repos/phpmetrics/PhpMetrics/releases/latest
    body_format: json
    return_content: true
  register: json_response

- name: Install PhpMetrics.
  become: true
  get_url:
    url: https://github.com/phpmetrics/PhpMetrics/releases/download/{{ json_response.json.tag_name }}/phpmetrics.phar
    dest: /usr/local/bin/phpmetrics
    mode: 0755
    force: true
